spring:
  application:
    name: spring-cloud-config-server
  security:
    user:
      name: admin
      password: password
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seenimurugan/config-parameters.git
          clone-on-start: true
server:
  port: 8888
  ssl:
    enabled: true
    key-store-type: JKS
    key-store: classpath:seenimurugan.jks
    key-store-password:
    key-alias: seenimurugan
logging:
  level:
    root: info
