spring:
  application:
    name: spring-cloud-config-server
  security:
    user:
      name: admin
      password: password
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seenimurugan/config-parameters.git
          clone-on-start: true
server:
  port: 8888
  httpPort: 80
  ssl:
    # openssl pkcs12 -export -out certificate.p12 -inkey private.key -in certificate.crt -certfile ca_bundle.crt -name seenimurugan
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:certificate.p12
    key-store-password:
    key-alias: seenimurugan
logging:
  level:
    root: info
